# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'Self Hosted Pool'

steps:
  - task: MSBuild@1
    displayName: 'Build DACPAC'
    inputs:
      solution: 'Jenkins-Fa-Snapshot-Ci-Pipeline.sln'
  # Create a secret variable
  - powershell: |
      $securePassword = ConvertTo-SecureString -String '$(pfaPassword)' -AsPlainText -Force
      $pfaCreds       = New-Object System.Management.Automation.PSCredential ( '$(pfaUsername)', '$securePassword' )
      $Targets = @('Z-STN-WIN2016-A\DEVOPSDEV1_AC')
      Invoke-PfaDbRefresh -RefreshDatabase tpch-no-compression `
                          -RefreshSource   Z-STN-WIN2016-A\DEVOPSPRD_AC `
                          -DestSqlInstance $Targets `
                          -PfaEndpoint     10.225.112.10 `
                          -PfaCredentials  $pfaCreds

  - script: echo $(System.DefaultWorkingDirectory)
    displayName: 'Apply DACPAC'

